name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Ensure Cypress is executable
        run: chmod +x ./node_modules/.bin/cypress  # Add this step

      - name: Run Cypress tests
        run: npx cypress run


      - name: Upload Mochawesome Reports
        if: always()  
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-reports  # Name of the uploaded artifact
          path: cypress/reports  # Path to the mochawesome reports
