name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5  # Cypress GitHub Action to manage everything
        with:
          runTests: true  # Automatically runs 'npx cypress run'

      - name: Upload Mochawesome Reports
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-reports
          path: cypress/reports
  
      - name: Upload Cypress screenshots
        if: always()  # This runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots  # The folder where Cypress saves screenshots