name: Run Cypress Tests

on:
  push:
    branches:
      - main  # Run tests when code is pushed to 'main' branch
  pull_request:   # Run tests on pull requests

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust the Node.js version to match your project

      - name: Install dependencies
        run: npm install  # Install the npm dependencies
      
      - name: Run Cypress tests
        run: npx cypress run  # Replace 'cy:run' with the npm script to run your Cypress tests

      - name: Upload Mochawesome Reports
        if: always()  # Always run this step, even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-reports  # Name of the uploaded artifact
          path: cypress/reports  # Path to the mochawesome reports
